export const INITIAL_NODES = [
  {
    id: 1,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 233,
      y: 174,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 2,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 188,
      y: 11,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 3,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 29,
      y: 239,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 4,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 165,
      y: 5,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 5,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 23,
      y: 66,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 6,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 60,
      y: 24,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 7,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 125,
      y: 271,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 8,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 287,
      y: 114,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 9,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 292,
      y: 188,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
  {
    id: 10,
    energy: 9000,
    clusterHead: null,
    nodes: null,
    position: {
      x: 76,
      y: 211,
      color: '#11bb00',
    },
    type: 'n',
    G: 0,
    isClusterHead: false,
    energies: [9000],
  },
];
